#!/usr/bin/env python3
"""
Folds Rendera session logs into docs/LEARNING.md.

## Why a workflow rather than the app pushing to GitHub

The app cannot write to a repository without a credential inside the APK, and a
personal access token in a published APK is public the moment it is uploaded.
The separation is deliberate: the app records, the user shares, this workflow
learns.

## Input

Any `*.jsonl` under `diagnostics/`, appended to by whoever is testing. Each line
is one record; `summary` lines carry the counters, `outcome` lines carry the
verdict on a dodge.

## What it does

Produces a table of sessions, the aggregated verdict on dodges, the most frequent
errors, and a list of every distinct failure with counts. The point is the last
one: a failure that has been reported five times and fixed once should not be
rediscovered from scratch next session.

Writes `docs/LEARNING.md` and commits it, appending rather than replacing, so the
history is visible.
"""

from __future__ import annotations

import collections
import glob
import json
import os
import sys

OUT = "docs/LEARNING.md"
MARK = "<!-- rendera:learning -->"


def load(paths: list[str]) -> list[dict]:
    records: list[dict] = []
    for p in paths:
        with open(p, "r", errors="replace") as fh:
            for line in fh:
                line = line.strip()
                if not line or line[0] != "{":
                    continue
                try:
                    records.append(json.loads(line))
                except json.JSONDecodeError:
                    # A truncated final line is expected when a log is pulled off
                    # a device mid-write, so a bad line is skipped, not fatal.
                    continue
    return records


def main() -> int:
    paths = sorted(glob.glob("diagnostics/*.jsonl"))
    if not paths:
        print("no diagnostics/*.jsonl found; nothing to fold")
        return 0

    records = load(paths)
    by_type = collections.Counter(r.get("type", "?") for r in records)
    print(f"{len(records)} records from {len(paths)} file(s): {dict(by_type)}")

    sessions = [r for r in records if r.get("type") == "session"]
    summaries = [r for r in records if r.get("type") == "summary"]
    outcomes = [r for r in records if r.get("type") == "outcome"]
    errors = [r for r in records if r.get("type") == "error"]
    decisions = [r for r in records if r.get("type") == "decision"]
    calibrations = [r for r in records if r.get("type") == "calibration"]

    worked = sum(1 for r in outcomes if r.get("worked") is True)
    failed = sum(1 for r in outcomes if r.get("worked") is False)
    dispatched = sum(1 for r in decisions if r.get("dispatched") is True)
    refused = sum(1 for r in decisions if r.get("dispatched") is False)
    work_rate = (worked / dispatched * 100.0) if dispatched else -1.0

    err_counts: collections.Counter = collections.Counter()
    for r in errors:
        err_counts[f"{r.get('tag')}: {r.get('msg')}"] += int(r.get("count", 1))

    auto_ok = sum(1 for r in calibrations if r.get("source") == "auto" and r.get("ok"))
    auto_runs = sum(1 for r in calibrations if r.get("source") == "auto")

    latest_samples = [r for r in records if r.get("type") == "sample"][-400:]
    fps = [int(r.get("fps", 0)) for r in latest_samples]
    frames = [int(r.get("analysed", 0)) for r in latest_samples]
    player_hits = sum(1 for r in latest_samples if r.get("player") is True)

    parts: list[str] = []
    parts.append(MARK)
    parts.append("")
    parts.append("<!-- Generated by .github/scripts/fold_learning.py. Do not edit by hand. -->")
    parts.append("")
    parts.append("# Rendera — what the device actually reported")
    parts.append("")
    parts.append(
        "Every number here came off a real device, through the app's own event log, "
        "not from reasoning. Read this before changing any tuning: it is the only "
        "record of what the detector did when it ran for real."
    )
    parts.append("")

    parts.append("## Sessions")
    parts.append("")
    parts.append("| started (UTC) | build | device | android |")
    parts.append("|---|---|---|---|")
    for s in sessions[-15:]:
        parts.append(
            f"| {s.get('t','?')} | {s.get('build','?')} | {s.get('device','?')} "
            f"| {s.get('android','?')} |"
        )
    if not sessions:
        parts.append("| _(none reported)_ | | | |")
    parts.append("")

    parts.append("## Did the dodges work")
    parts.append("")
    parts.append("This is the number the project never had. `dispatched` is how many")
    parts.append("gestures the system actually accepted; `worked` is how many threats then")
    parts.append("stopped being on a collision course.")
    parts.append("")
    parts.append(f"- gestures dispatched: **{dispatched}**")
    parts.append(f"- gestures refused: **{refused}**")
    parts.append(f"- dodges that worked: **{worked}**")
    parts.append(f"- dodges that did not: **{failed}**")
    if dispatched:
        parts.append(f"- **work rate: {work_rate:.0f}% of dispatched gestures**")
    else:
        parts.append("- work rate: n/a, nothing was dispatched")
    parts.append("")

    parts.append("## Detection throughput")
    parts.append("")
    if fps:
        parts.append(f"- fps: min {min(fps)}, median {sorted(fps)[len(fps)//2]}, max {max(fps)}")
        parts.append(f"- frames analysed in the last samples: {frames[-1] if frames else 0}")
    else:
        parts.append("- no samples reported, so no frames were analysed")
    parts.append(f"- player locked in {player_hits} of {len(latest_samples)} samples")
    parts.append("")

    parts.append("## Auto detect")
    parts.append("")
    if auto_runs:
        parts.append(f"- succeeded {auto_ok} of {auto_runs} attempts")
    else:
        parts.append("- never attempted")
    parts.append("")

    parts.append("## Errors, most frequent first")
    parts.append("")
    if err_counts:
        parts.append("| count | error |")
        parts.append("|---|---|")
        for msg, n in err_counts.most_common(25):
            parts.append(f"| {n} | {msg} |")
    else:
        parts.append("_No errors were reported._")
    parts.append("")

    parts.append("## Distinct failures, so they are not rediscovered")
    parts.append("")
    if err_counts:
        for i, (msg, n) in enumerate(err_counts.most_common(25), 1):
            parts.append(f"{i}. **{msg}** — seen {n} time(s)")
    else:
        parts.append("_Nothing._")
    parts.append("")

    text = "\n".join(parts) + "\n"

    # Append rather than replace, so the history is visible.
    prior = ""
    if os.path.exists(OUT):
        with open(OUT, "r", errors="replace") as fh:
            prior = fh.read()
    header = ""
    if MARK in prior:
        # Keep everything above the marker from a previous run, drop the old body.
        header = prior[: prior.index(MARK)]
    else:
        header = prior

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write(header + text)

    print(f"wrote {OUT} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
